# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# BANNER
banner:
  charset: UTF-8

# LOGGING
logging:
  level:
    root: INFO
    br.com.eigmercados: INFO
    
# WEB PROPERTIES
server:
  port: 20260
  context-path: /biometria
  compression:
    enabled: true
    mime-types:
    - text/html
    - text/css
    - application/json
    - text/javascript
    min-response-size: 1024

spring:
  # INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8

  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
---  

# Profile de desenvolvimento
spring:
  profiles: dev
  # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    url: jdbc:postgresql://prod05062017.cuec8amswoad.sa-east-1.rds.amazonaws.com:5432/snrd
    username: eigmercados
    password: eigmercado$
    driverClassName: org.postgresql.Driver
    tomcat:
      initial-size: 1
      max-idle: 10
      max-active: 10

# LOGGING
logging:
  file: /tmp/biometria.log
  
---

# Profile de producao
spring:
  profiles: prd
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    url: jdbc:postgresql://snrd.cuec8amswoad.sa-east-1.rds.amazonaws.com:5432/snrd
    username: eigmercados
    password: eigmercado$
    driverClassName: org.postgresql.Driver
    tomcat:
      initial-size: 1
      max-idle: 10
      max-active: 10
      
# LOGGING
logging:
  file: /var/log/biometria.log